source 'https://rubygems.org'
group :production do
  gem 'pg', '0.12.2'
end
gem 'rails', '3.2.11'
gem 'mysql2'
gem 'will_paginate', '3.0.4'
gem 'haml-rails'
gem 'rails_admin'
gem 'fancybox-rails'
gem 'carrierwave'
gem 'rails_admin_jcrop'
gem 'kaminari'

group :development, :test do
  gem 'rspec-rails'
  gem 'cucumber-rails', :require => false
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'email_spec'
  gem 'timecop'
  gem 'launchy'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'

  gem 'therubyracer', :platforms => :ruby
  gem 'twitter-bootstrap-rails'
  gem 'less-rails'
end

gem 'jquery-rails'
gem "tire"
gem "devise"
gem 'stripe'
gem 'paperclip', '~> 3.0'
